### ISSUE TITLE
Please consider a less generic repostiory name

### ISSUE THREAD

**Issue by unixorn** [tariqdomi/ohmyzsh-domixgit#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it `domixgit` to match the plugin file name.

Thanks!

**Comment by tariqdomi** [comment]
repository name is now: "ohmyzsh-domixgit"
